server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halcyonsdev/tinder-config-repo.git
    bus:
      enabled: true
      id: config-server
    stream:
      kafka:
        binder:
          brokers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: '*'
