server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/halcyonsdev/tinder-config-repo.git
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: '*'
