version: "3.8"

services:
  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: .
      dockerfile: microservices/user-service/Dockerfile
    ports:
      - "8080:${USER_SERVICE_PORT}"
    env_file:
      - microservices/user-service/.env
    depends_on:
      - user-postgres
    networks:
      - user-network
    restart: always

  user-postgres:
    image: postgres:17.2
    container_name: user-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:${USER_POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
    env_file:
      - microservices/user-service/.env
    networks:
      - user-network
    restart: always

networks:
  user-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local