apiVersion: v1
kind: Service
metadata:
  name: swipe-service
spec:
  selector:
    app: swipe-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30003
  type: NodePort
