apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: halcyons/user-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: POSTGRES_URL
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: POSTGRES_PASSWORD

            - name: JWT_SECRET_ACCESS
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: JWT_SECRET_ACCESS
            - name: JWT_SECRET_REFRESH
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: JWT_SECRET_REFRESH

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: REDIS_PORT

            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: MINIO_BUCKET
            - name: MINIO_HOST
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: MINIO_HOST
            - name: MINIO_PORT
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: MINIO_PORT

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: GRPC_PORT
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: GRPC_PORT
