apiVersion: v1
kind: Service
metadata:
  name: user-service-external
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
