apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  POSTGRES_URL: "jdbc:postgresql://user-postgres:5433/user_service"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "password"
  JWT_SECRET_ACCESS: "LA4XZ8oPuhwbaGHpPZBA7j6AzdnaufJxcA3BqN8qu/c/1mKklF+60Ds0PH4W/+yDXtZ4Ptaij135LReqleMEwg=="
  JWT_SECRET_REFRESH: "40bibBIBBT9lhB4xcAq4PqxBBkpi0Gw5okd8GrlGaLzIYjSPfTG1Xc+WPT0UxqXfyDV4P5WuPMecRkwM+e8c5Q=="
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MINIO_ROOT_USER: "minio"
  MINIO_ROOT_PASSWORD: "password"
  MINIO_BUCKET: "tinder"
  MINIO_HOST: "minio"
  MINIO_PORT: "9000"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  GRPC_PORT: "9090"
