apiVersion: v1
kind: Secret
metadata:
  name: config-service-secret
type: Opaque
stringData:
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/halcyonsdev/tinder-config-repo.git"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
