apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: halcyons/auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: REDIS_PORT
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: JWT_SECRET_ACCESS
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET_ACCESS
            - name: JWT_SECRET_REFRESH
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET_REFRESH
