name: Build and Test

on:
  push:
    branches:
      - main
      - user-service
  pull_request:
    branches:
      - main
      - user-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test/